name: environmentalist
description: Dumps all sufficient information about the platform for debugging purposes
repository: https://github.com/alexeyinkin/dart-environmentalist
version: 0.1.1

environment:
  sdk: ^3.0.0

dependencies:
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
